// runner script, to create

/**
 * a simple script runner, to test the bundler and API.
 * for a simple target method, we just call the "nonce" method of the account itself.
 */

import path from 'path'
import { BigNumber, ContractFactory, Signer, Wallet } from 'ethers'
import { JsonRpcProvider } from '@ethersproject/providers'
import { arrayify } from 'ethers/lib/utils'
import { formatEther, keccak256, parseEther } from 'ethers/lib/utils'
import { Command } from 'commander'
import { DeterministicDeployer, erc4337RuntimeVersion, SimpleAccountFactory__factory } from '@account-abstraction/utils'
import fs from 'fs'
import { HttpRpcClient, SimpleAccountAPI, SimplePaymasterAPI } from '@account-abstraction/sdk'
import { runBundler } from '../runBundler'
import { BundlerServer } from '../BundlerServer'
import { getNetworkProvider } from '../Config'
import {
  callGetUserOpHashWithCode,
  EIP_7702_MARKER_INIT_CODE,
  IEntryPoint__factory,
  UserOperation
} from '@account-abstraction/utils'
import { signEip7702Authorization } from './eip7702helpers'
import { ecsign, toRpcSig } from 'ethereumjs-util'

const ENTRY_POINT = '0x4337084D9E255Ff0702461CF8895CE9E3b5Ff108'

class Runner {
  bundlerProvider!: HttpRpcClient
  accountApi!: SimpleAccountAPI

  /**
   *
   * @param provider - a provider for initialization. This account is used to fund the created account contract, but it is not the account or its owner.
   * @param bundlerUrl - a URL to a running bundler. must point to the same network the provider is.
   * @param accountOwner - the wallet signer account. used only as signer (not as transaction sender)
   * @param entryPointAddress - the entrypoint address to use.
   * @param index - unique salt, to allow multiple accounts with the same owner
   */
  constructor (
    readonly provider: JsonRpcProvider,
    readonly bundlerUrl: string,
    readonly accountOwner: Signer,
    readonly entryPointAddress = ENTRY_POINT,
    readonly index = 0
  ) {
  }

  async getAddress (): Promise<string> {
    return await this.accountApi.getCounterFactualAddress()
  }

  async init (deploymentSigner?: Signer, paymasterAddress?: string): Promise<this> {
    const net = await this.provider.getNetwork()
    const chainId = net.chainId
    const dep = new DeterministicDeployer(this.provider)
    const accountDeployer = await DeterministicDeployer.getAddress(new SimpleAccountFactory__factory(), 0, [this.entryPointAddress])
    // const accountDeployer = await new SimpleAccountFactory__factory(this.provider.getSigner()).deploy().then(d=>d.address)
    if (!await dep.isContractDeployed(accountDeployer)) {
      if (deploymentSigner == null) {
        console.log(`AccountDeployer not deployed at ${accountDeployer}. run with --deployFactory`)
        process.exit(1)
      }
      const dep1 = new DeterministicDeployer(deploymentSigner.provider as any, deploymentSigner)
      // CREATE2 proxy 배포 후, Factory 배포 시 estimateGas가 revert하는 경우가 있어 gasLimit 명시
      const deployTx = await dep1.getDeployTransaction(new SimpleAccountFactory__factory(), 0, [this.entryPointAddress])
      ;(deployTx as any).gasLimit = 3_000_000
      await deploymentSigner.sendTransaction(deployTx)
    }
    this.bundlerProvider = new HttpRpcClient(this.bundlerUrl, this.entryPointAddress, chainId)
    
    const paymasterAPI = paymasterAddress != null
      ? new SimplePaymasterAPI(paymasterAddress)
      : undefined

    console.log('paymasterAPI', paymasterAPI)
    
    this.accountApi = new SimpleAccountAPI({
      provider: this.provider,
      entryPointAddress: this.entryPointAddress,
      factoryAddress: accountDeployer,
      owner: this.accountOwner,
      index: this.index,
      paymasterAPI
    })
    return this
  }

  parseExpectedGas (e: Error): Error {
    // parse a custom error generated by the BundlerHelper, which gives a hint of how much payment is missing
    const match = e.message?.match(/paid (\d+) expected (\d+)/)
    if (match != null) {
      const paid = Math.floor(parseInt(match[1]) / 1e9)
      const expected = Math.floor(parseInt(match[2]) / 1e9)
      return new Error(`Error: Paid ${paid}, expected ${expected} . Paid ${Math.floor(paid / expected * 100)}%, missing ${expected - paid} `)
    }
    return e
  }

  async runUserOp (target: string, data: string, waitForReceipt = true): Promise<string | null> {
    const userOp = await this.accountApi.createSignedUserOp({
      target,
      data
    })
    try {
      console.log('userOp', userOp)
      const userOpHash = await this.bundlerProvider.sendUserOpToBundler(userOp)
      console.log('✅ UserOp submitted:', userOpHash)
      
      if (waitForReceipt) {
        // Wait for receipt with 10 second timeout
        const startTime = Date.now()
        const timeout = 10000 // 10 seconds
        let txHash: string | null = null
        
        while (txHash == null && (Date.now() - startTime) < timeout) {
          await new Promise(resolve => setTimeout(resolve, 500))
          try {
            const receipt = await this.accountApi.getUserOpReceipt(userOpHash)
            if (receipt) {
              txHash = receipt
              break
            }
          } catch (e) {
            // Continue waiting
          }
        }
        
        if (txHash) {
          console.log('✅ Success! TxHash:', txHash)
        } else {
          console.log('⏱️ Timeout')
        }
        return txHash
      } else {
        return null
      }
    } catch (e: any) {
      throw this.parseExpectedGas(e)
    }
  }
}

async function main (): Promise<void> {
  const program = new Command()
    .version(erc4337RuntimeVersion)
    .option('--network <string>', 'network name or url', 'http://localhost:8545')
    .option('--mnemonic <file>', 'mnemonic/private-key file of signer account (to fund account)')
    .option('--bundlerUrl <url>', 'bundler URL', 'http://localhost:4000/rpc')
    .option('--entryPoint <string>', 'address of the supported EntryPoint contract', ENTRY_POINT)
    .option('--nonce <number>', 'account creation nonce. default to random (deploy new account)')
    .option('--deployFactory', 'Deploy the "account deployer" on this network (default for testnet)')
    .option('--show-stack-traces', 'Show stack traces.')
    .option('--selfBundler', 'run bundler in-process (for debugging the bundler)')
    .option('--paymaster <address>', 'paymaster contract address for gasless transactions')
    .option('--eip7702', 'Use EIP-7702 mode (delegate account)')

  const opts = program.parse().opts()
  const provider = getNetworkProvider(opts.network)
  let signer: Signer
  let deployFactory: boolean = opts.deployFactory
  let bundler: BundlerServer | undefined
  if (opts.selfBundler != null) {
    // todo: if node is geth, we need to fund our bundler's account:
    const signer = provider.getSigner()

    const signerBalance = await provider.getBalance(signer.getAddress())
    const account = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    const bal = await provider.getBalance(account)
    if (bal.lt(parseEther('1')) && signerBalance.gte(parseEther('10000'))) {
      console.log('funding hardhat account', account)
      await signer.sendTransaction({
        to: account,
        value: parseEther('1').sub(bal)
      })
    }

    const argv = ['node', 'exec', '--config', './localconfig/bundler.config.json', '--unsafe', '--auto']
    if (opts.entryPoint != null) {
      argv.push('--entryPoint', opts.entryPoint)
    }
    bundler = await runBundler(argv)
    await bundler.asyncStart()
  }
  if (opts.mnemonic != null) {
    signer = Wallet.fromMnemonic(fs.readFileSync(opts.mnemonic, 'ascii').trim()).connect(provider)
  } else {
    try {
      const accounts = await provider.listAccounts()
      if (accounts.length === 0) {
        console.log('fatal: no account. use --mnemonic (needed to fund account)')
        process.exit(1)
      }
      // for hardhat/node, use account[0]
      signer = provider.getSigner()
      const network = await provider.getNetwork()
      if (network.chainId === 1337 || network.chainId === 31337) {
        deployFactory = true
      }
    } catch (e) {
      throw new Error('must specify --mnemonic')
    }
  }
  const accountOwner = new Wallet('0x'.padEnd(66, '7'))

  const index = opts.nonce ?? Date.now()
  console.log('using account index=', index)
  const paymasterAddress = opts.paymaster
  if (paymasterAddress != null) {
    console.log('using paymaster address=', paymasterAddress)
  }

  // EIP-7702 모드 처리
  if (opts.eip7702) {
    console.log('🚀 EIP-7702 모드로 실행합니다')
    await runEip7702Test(provider, signer, opts.bundlerUrl, opts.entryPoint, accountOwner, paymasterAddress)
    await bundler?.stop()
    return
  }

  const client = await new Runner(provider, opts.bundlerUrl, accountOwner, opts.entryPoint, index).init(deployFactory ? signer : undefined, paymasterAddress)

  const addr = await client.getAddress()

  async function isDeployed (addr: string): Promise<boolean> {
    return await provider.getCode(addr).then(code => code !== '0x')
  }

  async function getBalance (addr: string): Promise<BigNumber> {
    return await provider.getBalance(addr)
  }

  const bal = await getBalance(addr)
  console.log('account address', addr, 'deployed=', await isDeployed(addr), 'bal=', formatEther(bal))

  // 넉넉하게 전송
  if(opts.paymaster == null) {
    await signer.sendTransaction({
      to: addr,
      value: parseEther('1')
    }).then(async tx => await tx.wait())
  }
  
  const dest = addr
  const data = keccak256(Buffer.from('entryPoint()')).slice(0, 10)
  console.log('data=', data)
  const txid1 = await client.runUserOp(dest, data, true)
  console.log('after run1, txid1=', txid1)
  
  // Wait a bit before sending second request to ensure first one is processed
  if (txid1 == null) {
    console.log('first transaction not yet mined, waiting...')
    await new Promise(resolve => setTimeout(resolve, 3000))
  }
  
  // client.accountApi.overheads!.perUserOp = 30000
  const txid2 = await client.runUserOp(dest, data, true)
  console.log('after run2, txid2=', txid2)
  await bundler?.stop()
}

async function runEip7702Test (
  provider: JsonRpcProvider,
  signer: Signer,
  bundlerUrl: string,
  entryPointAddress: string,
  accountOwner: Wallet,
  _paymasterAddress?: string
): Promise<void> {
  console.log('\n========== EIP-7702 테스트 시작 ==========')
  
  // 1. Simple7702Account delegate 배포 (JSON 아티팩트 사용, Hardhat 미의존)
  console.log('📦 Simple7702Account delegate 배포 중...')
  const artifactPath = path.join(__dirname, '../../../../submodules/account-abstraction/artifacts/contracts/accounts/Simple7702Account.sol/Simple7702Account.json')
  const artifact = require(artifactPath)
  const delegateFactory = new ContractFactory(artifact.abi, artifact.bytecode, signer)
  const delegate = await delegateFactory.deploy()
  await delegate.deployed()
  const delegateAddress = delegate.address
  console.log('✅ Delegate 배포 완료:', delegateAddress)

  // 2. EntryPoint 연결 (utils에서 제공)
  const entryPoint = IEntryPoint__factory.connect(entryPointAddress, provider)
  const chainId = (await provider.getNetwork()).chainId

  // 3. EOA (accountOwner)
  const eoa = accountOwner.connect(provider) as Wallet
  const eoaAddress = await eoa.getAddress()
  console.log('👤 EOA 주소:', eoaAddress)

  // 4. EOA에 ETH 전송 (필요한 경우)
  const eoaBalance = await provider.getBalance(eoaAddress)
  if (eoaBalance.lt(parseEther('0.1'))) {
    console.log('💰 EOA에 ETH 전송 중...')
    await signer.sendTransaction({
      to: eoaAddress,
      value: parseEther('1')
    }).then(async tx => await tx.wait())
    console.log('✅ ETH 전송 완료')
  }

  // 5. EIP-7702 authorization 생성
  console.log('🔐 EIP-7702 authorization 생성 중...')
  const auth = await signEip7702Authorization(eoa, {
    chainId,
    nonce: 0,
    address: delegateAddress
  })
  const authWithNonce = { ...auth, nonce: auth.nonce ?? 0 }
  console.log('✅ Authorization 생성 완료')

  // 6. UserOperation 구성 (factory = 0x7702 마커, 가스는 기본값)
  console.log('📝 UserOperation 생성 중...')
  const callData = delegate.interface.encodeFunctionData('execute', [eoaAddress, 0, '0x'])
  const feeData = await provider.getFeeData()
  const maxPriorityFeePerGas = feeData.maxPriorityFeePerGas ?? BigNumber.from(1e9)
  const maxFeePerGas = feeData.maxFeePerGas?.add(maxPriorityFeePerGas) ?? maxPriorityFeePerGas.mul(2)
  const partialUserOp: UserOperation = {
    sender: eoaAddress,
    nonce: 0,
    factory: EIP_7702_MARKER_INIT_CODE,
    factoryData: '0x',
    callData,
    callGasLimit: 100000,
    verificationGasLimit: 200000,
    preVerificationGas: 50000,
    maxFeePerGas,
    maxPriorityFeePerGas,
    signature: '0x'
  }
  const userOpWithAuth: UserOperation = {
    ...partialUserOp,
    eip7702Auth: authWithNonce
  }

  // 7. getUserOpHash (7702 state override 적용) 후 서명
  const userOpHashHex = await callGetUserOpHashWithCode(entryPoint, userOpWithAuth)
  const sig = ecsign(Buffer.from(arrayify(userOpHashHex)), Buffer.from(arrayify(eoa.privateKey)))
  const signature = toRpcSig(sig.v, sig.r, sig.s)
  const finalUserOp: UserOperation = { ...userOpWithAuth, signature }

  console.log('✅ UserOperation 생성 완료')
  console.log('  - Sender:', finalUserOp.sender)
  console.log('  - Factory (7702):', finalUserOp.factory)
  console.log('  - CallData:', finalUserOp.callData)

  // 8. Bundler에 UserOperation 전송
  console.log('📤 Bundler에 UserOperation 전송 중...')
  const bundlerProvider = new HttpRpcClient(bundlerUrl, entryPointAddress, chainId)
  
  try {
    const userOpHash = await bundlerProvider.sendUserOpToBundler(finalUserOp)
    console.log('✅ UserOperation 전송 완료, Hash:', userOpHash)

    // 9. Receipt 대기
    console.log('⏳ Receipt 대기 중...')
    let receipt: string | null = null
    let attempts = 0
    while (receipt == null && attempts < 60) {
      await new Promise(resolve => setTimeout(resolve, 1000))
      const accountApi = new SimpleAccountAPI({
        provider,
        entryPointAddress,
        owner: eoa,
        factoryAddress: '0x' // 7702 모드에서는 사용하지 않음
      })
      receipt = await accountApi.getUserOpReceipt(userOpHash).catch(() => null)
      attempts++
    }

    if (receipt != null) {
      console.log('✅ 트랜잭션 완료, Receipt:', receipt)
    } else {
      console.log('⚠️ Receipt를 받지 못했습니다 (타임아웃)')
    }
  } catch (e: any) {
    console.error('❌ UserOperation 전송 실패:', e.message)
    throw e
  }

  console.log('========== EIP-7702 테스트 완료 ==========\n')
}

void main()
  .catch(e => { console.log(e); process.exit(1) })
  .then(() => process.exit(0))
